sudo: false
language: node_js
node_js:
  - "0.10"
  - "4.0"
  - "4.1"
  - "stable"
before_install:
  - npm install -g grunt-cli
after_script:
  - mocha -t 60000 --require blanket --reporter mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js
after_success:
  - if [ $TRAVIS_NODE_VERSION = '0.10' ] && [ $TRAVIS_BRANCH = 'master' ] && [ $TRAVIS_PULL_REQUEST = 'false' ];